---
Files:
  main.tf:
    mandatory: true
    authorized_blocks:
  variables.tf:
    mandatory: true
    authorized_blocks:
      - variable
  outputs.tf:
    mandatory: true
    authorized_blocks:
      - output
  provider.tf:
    mandatory: true
    authorized_blocks:
      - provider
  backend.tf:
    mandatory: true
    authorized_blocks:
      - terraform
  default:
    mandatory: false
    authorized_blocks:
      - resource
      - module
      - data
      - locals
ensure_terraform_version: true
ensure_providers_version: true
ensure_readme_updated: true
block_pattern_name: "^[a-z0-9_]*$"
